In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df = sns.load_dataset('tips')

In [74]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [76]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [77]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [78]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

# feature encoding - label and OHE

In [79]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [80]:
X= df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [81]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [82]:
X_train.head()

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2

In [83]:
y_train.head()

115    17.31
181    23.33
225    16.27
68     20.23
104    20.92
Name: total_bill, dtype: float64

In [84]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [85]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['day'] = le3.fit_transform(X_train['day'])

In [86]:
X_train.head()

      tip  sex  smoker  day    time  size
115  3.50    0       0    2  Dinner     2
181  5.65    1       1    2  Dinner     2
225  2.50    0       1    0   Lunch     2
68   2.01    1       0    1  Dinner     2
104  4.08    0       0    1  Dinner     2

In [87]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['day'] = le3.transform(X_test['day'])

In [88]:
X_test.head()

      tip  sex  smoker  day    time  size
24   3.18    1       0    1  Dinner     2
6    2.00    1       0    2  Dinner     2
153  2.00    1       0    2  Dinner     4
211  5.16    1       1    1  Dinner     4
198  2.00    0       1    3   Lunch     2

In [89]:
## OHE for day

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [90]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [91]:
X_train=ct.fit_transform(X_train)

In [92]:
X_train

array([[0.0, 1.0, 0.0, ..., 0, 'Dinner', 2],
       [0.0, 1.0, 0.0, ..., 1, 'Dinner', 2],
       [0.0, 0.0, 0.0, ..., 1, 'Lunch', 2],
       ...,
       [0.0, 0.0, 0.0, ..., 1, 'Dinner', 2],
       [0.0, 1.0, 0.0, ..., 1, 'Dinner', 2],
       [1.0, 0.0, 0.0, ..., 1, 'Dinner', 3]], dtype=object)

In [93]:
X_test=ct.transform(X_test)

In [94]:
X_test

array([[1.0, 0.0, 0.0, 3.18, 1, 0, 'Dinner', 2],
       [0.0, 1.0, 0.0, 2.0, 1, 0, 'Dinner', 2],
       [0.0, 1.0, 0.0, 2.0, 1, 0, 'Dinner', 4],
       [1.0, 0.0, 0.0, 5.16, 1, 1, 'Dinner', 4],
       [0.0, 0.0, 1.0, 2.0, 0, 1, 'Lunch', 2],
       [0.0, 1.0, 0.0, 2.0, 1, 1, 'Dinner', 2],
       [0.0, 0.0, 1.0, 2.56, 1, 1, 'Lunch', 2],
       [0.0, 0.0, 1.0, 2.52, 0, 0, 'Lunch', 2],
       [0.0, 1.0, 0.0, 3.23, 1, 0, 'Dinner', 2],
       [0.0, 0.0, 0.0, 3.0, 0, 1, 'Dinner', 2],
       [0.0, 1.0, 0.0, 3.0, 1, 0, 'Dinner', 2],
       [1.0, 0.0, 0.0, 1.47, 1, 0, 'Dinner', 2],
       [0.0, 0.0, 1.0, 1.5, 0, 0, 'Lunch', 2],
       [0.0, 1.0, 0.0, 2.0, 1, 1, 'Dinner', 2],
       [0.0, 0.0, 1.0, 1.83, 0, 0, 'Lunch', 1],
       [0.0, 0.0, 1.0, 1.36, 0, 0, 'Lunch', 3],
       [0.0, 0.0, 1.0, 4.0, 1, 1, 'Lunch', 3],
       [0.0, 1.0, 0.0, 3.92, 1, 0, 'Dinner', 2],
       [1.0, 0.0, 0.0, 2.47, 0, 0, 'Dinner', 2],
       [0.0, 0.0, 1.0, 5.0, 1, 0, 'Lunch', 5],
       [1.0, 0.0, 0.0, 2.45, 0, 0, 'Dinner', 4],
       [1.0, 0.0, 0.0, 3.35, 1, 0, 'Dinner', 3],
       [1.0, 0.0, 0.0, 4.0, 0, 1, 'Dinner', 2],
       [1.0, 0.0, 0.0, 1.45, 1, 0, 'Dinner', 2],
       [0.0, 1.0, 0.0, 3.5, 0, 1, 'Dinner', 3],
       [0.0, 0.0, 1.0, 2.31, 1, 0, 'Lunch', 2],
       [0.0, 1.0, 0.0, 1.71, 1, 0, 'Dinner', 2],
       [1.0, 0.0, 0.0, 5.0, 0, 1, 'Dinner', 2],
       [0.0, 1.0, 0.0, 2.0, 1, 0, 'Dinner', 4],
       [0.0, 1.0, 0.0, 5.0, 1, 0, 'Dinner', 6],
       [0.0, 1.0, 0.0, 4.0, 1, 0, 'Dinner', 3],
       [1.0, 0.0, 0.0, 1.44, 1, 1, 'Dinner', 2],
       [1.0, 0.0, 0.0, 2.34, 1, 0, 'Dinner', 4],
       [1.0, 0.0, 0.0, 3.21, 1, 1, 'Dinner', 2],
       [0.0, 1.0, 0.0, 3.5, 0, 0, 'Dinner', 3],
       [0.0, 0.0, 1.0, 2.92, 0, 0, 'Lunch', 4],
       [0.0, 0.0, 0.0, 1.5, 1, 1, 'Dinner', 2],
       [0.0, 0.0, 1.0, 5.0, 0, 1, 'Lunch', 4],
       [0.0, 0.0, 1.0, 2.75, 0, 0, 'Lunch', 2],
       [1.0, 0.0, 0.0, 2.0, 1, 1, 'Dinner', 2],
       [1.0, 0.0, 0.0, 1.25, 1, 0, 'Dinner', 2],
       [0.0, 0.0, 1.0, 2.0, 0, 0, 'Lunch', 2],
       [0.0, 1.0, 0.0, 2.55, 1, 0, 'Dinner', 2],
       [0.0, 1.0, 0.0, 1.67, 0, 0, 'Dinner', 3],
       [0.0, 0.0, 1.0, 2.0, 1, 1, 'Lunch', 2],
       [1.0, 0.0, 0.0, 1.0, 0, 1, 'Dinner', 1],
       [1.0, 0.0, 0.0, 1.61, 0, 1, 'Dinner', 2],
       [1.0, 0.0, 0.0, 2.31, 1, 0, 'Dinner', 3],
       [0.0, 0.0, 1.0, 1.44, 1, 0, 'Lunch', 2],
       [1.0, 0.0, 0.0, 2.72, 1, 0, 'Dinner', 2],
       [1.0, 0.0, 0.0, 2.03, 1, 1, 'Dinner', 2],
       [0.0, 0.0, 0.0, 4.0, 1, 1, 'Dinner', 2],
       [0.0, 1.0, 0.0, 4.5, 1, 0, 'Dinner', 4],
       [0.0, 0.0, 1.0, 2.03, 1, 0, 'Lunch', 2],
       [0.0, 1.0, 0.0, 3.51, 1, 0, 'Dinner', 2],
       [0.0, 0.0, 1.0, 2.0, 1, 0, 'Lunch', 2],
       [0.0, 1.0, 0.0, 5.15, 1, 1, 'Dinner', 2],
       [1.0, 0.0, 0.0, 1.75, 1, 0, 'Dinner', 2],
       [0.0, 1.0, 0.0, 2.74, 1, 0, 'Dinner', 3],
       [1.0, 0.0, 0.0, 3.0, 1, 1, 'Dinner', 3],
       [0.0, 1.0, 0.0, 5.14, 0, 0, 'Dinner', 5]], dtype=object)