In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
df = sns.load_dataset('tips')

In [130]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [132]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [133]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [134]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [135]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

# feature encoding - label and OHE

In [136]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [137]:
X= df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [138]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [139]:
X_train.head()

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2

In [140]:
y_train.head()

115    17.31
181    23.33
225    16.27
68     20.23
104    20.92
Name: total_bill, dtype: float64

In [141]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [142]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['day'] = le3.fit_transform(X_train['time'])

In [143]:
X_train.head()

      tip  sex  smoker  day    time  size
115  3.50    0       0    0  Dinner     2
181  5.65    1       1    0  Dinner     2
225  2.50    0       1    1   Lunch     2
68   2.01    1       0    0  Dinner     2
104  4.08    0       0    0  Dinner     2

In [144]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['day'] = le3.transform(X_test['time'])

In [145]:
X_test.head()

      tip  sex  smoker  day    time  size
24   3.18    1       0    0  Dinner     2
6    2.00    1       0    0  Dinner     2
153  2.00    1       0    0  Dinner     4
211  5.16    1       1    0  Dinner     4
198  2.00    0       1    1   Lunch     2

In [146]:
## OHE for day

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [147]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first'),['time'])],remainder='passthrough')

In [148]:
X_train=ct.fit_transform(X_train)

In [149]:
X_train

array([[0.  , 3.5 , 0.  , 0.  , 0.  , 2.  ],
       [0.  , 5.65, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 2.5 , 0.  , 1.  , 1.  , 2.  ],
       ...,
       [0.  , 1.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 3.55, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 2.5 , 0.  , 1.  , 0.  , 3.  ]])

In [150]:
X_test=ct.transform(X_test)

In [151]:
X_test

array([[0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 3.92, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.45, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 5.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 5.  , 1.  , 0.  , 0.  , 6.  ],
       [0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.44, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 3.5 , 0.  , 0.  , 0.  , 3.  ],
       [1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [1.  , 2.75, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 2.55, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.67, 0.  , 0.  , 0.  , 3.  ],
       [1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.61, 0.  , 1.  , 0.  , 2.  ],
       [0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 2.72, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 2.03, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 4.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 4.5 , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 2.03, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 2.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 5.15, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.75, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 2.74, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 3.  , 1.  , 1.  , 0.  , 3.  ],
       [0.  , 5.14, 0.  , 0.  , 0.  , 5.  ]])

In [152]:
from sklearn.svm import SVR
svr = SVR()

In [153]:
svr.fit(X_train,y_train)

SVR()

In [154]:
y_pred = svr.predict(X_test)

In [155]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [156]:
print('MAE:',mean_absolute_error(y_test,y_pred))
print('MSE:',mean_squared_error(y_test,y_pred))
print('R2 Score:',r2_score(y_test,y_pred))

MAE: 4.415651069977588
MSE: 39.08593045705571
R2 Score: 0.5008632808282296

In [157]:
## Hyperparameter Tuning

In [158]:
from sklearn.model_selection import GridSearchCV

params = {
    'kernel':['linear','rbf','poly'],
    'C':[0.1,1,10,100],
    'gamma':[1,0.1,0.01,0.001]
}

In [159]:
grid = GridSearchCV(SVR(),params,refit=True,verbose=3)

grid.fit(X_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.509 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.653 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.386 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.638 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.204 total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.001 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.006 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.007 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.116 total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.564 total time=   0.1s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.136 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.054 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.454 total time=   0.1s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.039 total time=   0.1s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.509 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.653 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.386 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.638 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.204 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.040 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.105 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.086 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.110 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.412 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.561 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.192 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.655 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.172 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.509 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.653 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.386 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.638 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.204 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.101 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.017 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.008 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.023 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.114 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.145 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.012 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.016 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.007 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.153 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.509 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.653 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.386 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.638 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.204 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.155 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.031 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.027 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.028 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.162 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.038 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.032 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.036 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.165 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=0.606 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1, kernel=linear;, score=0.384 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1, kernel=linear;, score=0.668 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1, kernel=linear;, score=0.221 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.220 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.284 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.264 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.179 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.155 total time=   0.0s
[CV 1/5] END .........C=1, gamma=1, kernel=poly;, score=0.485 total time=   1.6s
[CV 2/5] END .........C=1, gamma=1, kernel=poly;, score=0.087 total time=   1.0s
[CV 3/5] END .........C=1, gamma=1, kernel=poly;, score=0.084 total time=   0.2s
[CV 4/5] END .........C=1, gamma=1, kernel=poly;, score=0.399 total time=   0.3s
[CV 5/5] END ........C=1, gamma=1, kernel=poly;, score=-0.438 total time=   0.7s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.606 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.384 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.668 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.221 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.524 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.468 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.333 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.429 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.216 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.574 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.521 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.155 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.653 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.222 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.606 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.384 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.668 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.01, kernel=linear;, score=0.221 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.199 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.376 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.268 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.372 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.088 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.01, kernel=poly;, score=-0.019 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.198 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.109 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.220 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.01, kernel=poly;, score=-0.053 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.606 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.384 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.668 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.221 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.094 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.031 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.015 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.037 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.106 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.162 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.038 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.032 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.036 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.165 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END ......C=10, gamma=1, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ......C=10, gamma=1, kernel=linear;, score=0.376 total time=   0.0s
[CV 4/5] END ......C=10, gamma=1, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END ......C=10, gamma=1, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.250 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.561 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.453 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.214 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.300 total time=   0.0s
[CV 1/5] END ........C=10, gamma=1, kernel=poly;, score=0.409 total time=  12.1s
[CV 2/5] END ........C=10, gamma=1, kernel=poly;, score=0.268 total time=   3.6s
[CV 3/5] END ........C=10, gamma=1, kernel=poly;, score=0.370 total time=   2.5s
[CV 4/5] END ........C=10, gamma=1, kernel=poly;, score=0.462 total time=   5.2s
[CV 5/5] END .......C=10, gamma=1, kernel=poly;, score=-0.336 total time=  13.4s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.376 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.585 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.621 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.414 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.566 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.257 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.623 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.443 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.102 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.547 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.161 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.376 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.01, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.552 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.631 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.391 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.627 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.219 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.223 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.588 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.311 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.626 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.095 total time=   0.0s
[CV 1/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.376 total time=   0.0s
[CV 4/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.232 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.460 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.302 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.444 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.113 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.160 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.036 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.031 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.033 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.164 total time=   0.0s
[CV 1/5] END .....C=100, gamma=1, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END .....C=100, gamma=1, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END .....C=100, gamma=1, kernel=linear;, score=0.375 total time=   0.0s
[CV 4/5] END .....C=100, gamma=1, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END .....C=100, gamma=1, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.517 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.443 total time=   0.0s
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.140 total time=   0.0s
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.011 total time=   0.0s
[CV 1/5] END .......C=100, gamma=1, kernel=poly;, score=0.340 total time= 1.6min
[CV 2/5] END .......C=100, gamma=1, kernel=poly;, score=0.327 total time=  36.6s
[CV 3/5] END ......C=100, gamma=1, kernel=poly;, score=-0.276 total time= 3.5min
[CV 4/5] END .......C=100, gamma=1, kernel=poly;, score=0.351 total time= 1.4min
[CV 5/5] END ......C=100, gamma=1, kernel=poly;, score=-0.194 total time= 2.0min
[CV 1/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.375 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.393 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.653 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.415 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.481 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.204 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.564 total time=   0.1s
[CV 2/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.136 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.054 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.454 total time=   0.1s
[CV 5/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.039 total time=   0.1s
[CV 1/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.375 total time=   0.0s
[CV 4/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END ..C=100, gamma=0.01, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.582 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.671 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.392 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.658 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.254 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.01, kernel=poly;, score=0.412 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.01, kernel=poly;, score=0.561 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.01, kernel=poly;, score=0.192 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.01, kernel=poly;, score=0.655 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.01, kernel=poly;, score=0.172 total time=   0.0s
[CV 1/5] END .C=100, gamma=0.001, kernel=linear;, score=0.624 total time=   0.0s
[CV 2/5] END .C=100, gamma=0.001, kernel=linear;, score=0.666 total time=   0.0s
[CV 3/5] END .C=100, gamma=0.001, kernel=linear;, score=0.375 total time=   0.0s
[CV 4/5] END .C=100, gamma=0.001, kernel=linear;, score=0.667 total time=   0.0s
[CV 5/5] END .C=100, gamma=0.001, kernel=linear;, score=0.243 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.558 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.660 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.387 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.656 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.221 total time=   0.0s
[CV 1/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.145 total time=   0.0s
[CV 2/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.012 total time=   0.0s
[CV 3/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.016 total time=   0.0s
[CV 4/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.007 total time=   0.0s
[CV 5/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.153 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=3)

In [160]:
grid.best_params_

{'C': 10, 'gamma': 1, 'kernel': 'linear'}

In [161]:
grid_pred = grid.predict(X_test)

In [162]:
print('MAE:',mean_absolute_error(y_test,grid_pred))
print('MSE:',mean_squared_error(y_test,grid_pred))
print('R2 Score:',r2_score(y_test,grid_pred))

MAE: 4.181079246573135
MSE: 32.41767976492773
R2 Score: 0.5860184436748855